# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# You can always specify higher scaling factors (<= 0.2) in your motion requests.
# Due to current controller constraints, values higher than 0.2 may cause unstable behavior.
default_velocity_scaling_factor: 0.1 # Please make sure to use values less than or equal to 0.2 only. 
default_acceleration_scaling_factor: 0.1 # Please make sure to use values less than or equal to 0.2 only.

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  j1:
    has_velocity_limits: true
    max_velocity: 2.0939999999999999
    has_acceleration_limits: true
    max_acceleration: 1.7746
  j2:
    has_velocity_limits: true
    max_velocity: 1.833
    has_acceleration_limits: true
    max_acceleration: 1.5939
  j3:
    has_velocity_limits: true
    max_velocity: 2.0070000000000001
    has_acceleration_limits: true
    max_acceleration: 2.23
  j4:
    has_velocity_limits: true
    max_velocity: 2.5310000000000001
    has_acceleration_limits: true
    max_acceleration: 4.9627
  j5:
    has_velocity_limits: true
    max_velocity: 2.5310000000000001
    has_acceleration_limits: true
    max_acceleration: 3.8938
  j6:
    has_velocity_limits: true
    max_velocity: 3.8399999999999999
    has_acceleration_limits: true
    max_acceleration: 7.3846