# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# You can always specify higher scaling factors (<= 0.2) in your motion requests.
# Due to current controller constraints, values higher than 0.2 may cause unstable behavior.
default_velocity_scaling_factor: 0.1 # Please make sure to use values less than or equal to 0.2 only. 
default_acceleration_scaling_factor: 0.1 # Please make sure to use values less than or equal to 0.2 only.

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  j1:
    has_velocity_limits: true
    max_velocity: 3.141
    has_acceleration_limits: true
    max_acceleration: 4.487
  j2:
    has_velocity_limits: true
    max_velocity: 3.141
    has_acceleration_limits: true
    max_acceleration: 3.306
  j3:
    has_velocity_limits: true
    max_velocity: 3.316
    has_acceleration_limits: true
    max_acceleration: 8.290
  j4:
    has_velocity_limits: true
    max_velocity: 5.410
    has_acceleration_limits: true
    max_acceleration: 18.033
  j5:
    has_velocity_limits: true
    max_velocity: 5.410
    has_acceleration_limits: true
    max_acceleration: 15.457
  j6:
    has_velocity_limits: true
    max_velocity: 7.330
    has_acceleration_limits: true
    max_acceleration: 29.32